<?php
// Require the configuration file to load the SDK and credentials
require_once __DIR__ . '/config.php';

// Check if the form was submitted via POST
if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    die("Invalid request method. Please submit the form.");
}

// Retrieve the token generated by CrafyCAPTCHA in the frontend.
// By default, the JS SDK injects a hidden input with the name 'CrafyCAPTCHA_token'.
// Ensure that this name matches the 'inputName' defined in your JS initialization.
$captchaToken = isset($_POST['CrafyCAPTCHA_token']) ? $_POST['CrafyCAPTCHA_token'] : null;

// Basic validation: Check if the token was received
if (!$captchaToken) {
    die("CAPTCHA token is missing. Please complete the CAPTCHA and try again.");
}

try {
    // Verify the flow using the PHP SDK.
    // This method validates the token signature, checks expiration, and consumes the Nonce (Anti-Replay).
    // It returns true if the token is valid, and false otherwise.
    $isValid = $global_CrafyCAPTCHA->verifyFlow($captchaToken);

    if ($isValid) {
        // The CAPTCHA was successfully verified. The user is legitimate.
        echo "<h1>Verification Successful!</h1>";
        echo "<p style='color: green;'>The CAPTCHA was valid. Proceeding with the action...</p>";
        
        // Here you would process the form data (e.g., login the user, save data to DB)
        $username = htmlspecialchars($_POST['username'] ?? 'Guest');
        echo "<p>Welcome, $username!</p>";
        echo "<a href='index.php'>Go back</a>";
        
    } else {
        // The verifyFlow returned false. 
        // Typically, errors throw Exceptions, but we handle a false return just in case.
        echo "<h1>Verification Failed!</h1>";
        echo "<p style='color: red;'>The CAPTCHA validation failed.</p>";
        echo "<a href='index.php'>Go back and try again</a>";
    }

} catch (Exception $e) {
    // An error occurred during verification (e.g., expired token, replayed token, invalid signature)
    echo "<h1>Verification Error!</h1>";
    echo "<p style='color: red;'>Error details: " . htmlspecialchars($e->getMessage()) . "</p>";
    echo "<p>Please go back and try again.</p>";
    echo "<a href='index.php'>Go back</a>";
}
